/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#13121b",
        "bg-base": "#0f1117",
        "bg-surface": "#1a1d27",
        "bg-elevated": "#242736",
        "text-primary": "#e8eaf0",
        "text-secondary": "#8b8fa8",
        accent: "#94a3b8",
        "surface-container-lowest": "#0e0d15",
        "surface-container-low": "#1c1b23",
        "surface-container": "#201f27",
        "surface-container-high": "#2a2932",
        "surface-container-highest": "#35343d",
        surface: "#13121b",
        "on-surface": "#e5e0ed",
        "on-surface-variant": "#c9c4d7",
        outline: "#928ea0",
        "outline-variant": "#242736",
        primary: "#94a3b8",
        "primary-container": "#b8c4d4",
        "on-primary": "#1e293b",
        "secondary-container": "#444652",
        "on-secondary-container": "#b2b4c2",
        "inverse-primary": "#6b7a90",
        tertiary: "#ffb86d",
        "success-green": "#4ade80",
        "accent-gray": "#8b8fa8",
        error: "#ffb4ab",
        "error-container": "#93000a",
        amber: "#fbbf24",
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        mono: ["Space Grotesk", "monospace"],
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        body: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "small-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        code: ["13px", { lineHeight: "18px", fontWeight: "400" }],
        h1: ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h2: ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
