/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: '#131317',
        'surface-dim': '#131317',
        'surface-bright': '#39393d',
        'surface-container-lowest': '#0e0e12',
        'surface-container-low': '#1b1b1f',
        'surface-container': '#1f1f23',
        'surface-container-high': '#2a292e',
        'surface-container-highest': '#353439',
        'on-surface': '#e4e1e7',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#e4e1e7',
        'inverse-on-surface': '#303034',
        outline: '#849495',
        'outline-variant': '#3a494b',
        'surface-tint': '#00dce6',
        primary: '#e0fdff',
        'on-primary': '#00373a',
        'primary-container': '#2563eb',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#00696f',
        'primary-fixed': '#6ff6ff',
        'primary-fixed-dim': '#00dce6',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f53',
        secondary: '#c0c1ff',
        'on-secondary': '#1000a9',
        'secondary-container': '#3131c0',
        'on-secondary-container': '#b0b2ff',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        'on-secondary-fixed': '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        tertiary: '#fff6e4',
        'on-tertiary': '#3b2f00',
        'tertiary-container': '#fed83a',
        'on-tertiary-container': '#725e00',
        'tertiary-fixed': '#ffe173',
        'tertiary-fixed-dim': '#e8c423',
        'on-tertiary-fixed': '#221b00',
        'on-tertiary-fixed-variant': '#554500',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#131317',
        'on-background': '#e4e1e7',
        'surface-variant': '#353439',
        'success-green': '#4ade80',
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-base': ['15px', { lineHeight: '1.5', letterSpacing: '-0.01em', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md-mobile': ['20px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        body: ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'small-mono': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        code: ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        'margin-desktop': '32px',
        'margin-mobile': '16px',
        'panel-width': '320px',
      },
    },
  },
  plugins: [],
};
